# Generated by Django 3.1.2 on 2020-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
